### ISSUE TITLE
No module named serial_tool.__main__; 'serial_tool' is a package and cannot be directly executed

### ISSUE THREAD

**Issue by Jesper117** [damogranlabs/serial-tool#2]
![image](https://github.com/damogranlabs/serial-tool/assets/20819903/d522a6a1-46f3-4c4e-ab35-1f0b0fc6cffc)

**Comment by schperplata** [comment]
Oh, thanks! 
Weird, nobody noticed (or reported) before. 

Fixed with: 72b559c1faf240fcda91b96d565a6ed3df87241d
